### ISSUE TITLE
Limit Meteor calls to current user and appropriate data

### ISSUE THREAD

**Issue by yacinemerzouk** [zendylabs/minos-pro#3]
## Minos.Challenge.cancel

* only available to challenger = Meteor.userId()
* only available if status = issued

## Minos.Challenge.issue

* user logged in
* opponent cannot be Meteor.userId()
* opponent id must exist
* timestamps must be generated by server
* status set by server
* challenger id set by server

## Minos.Challenge.refuse

* timestamp set by server
* opponent has to be Meteor.userId()
* status set by server

## Minos.Challenge.accept

* timestamp set by server
* opponent has to be Meteor.userId()
* status set by server

## Any DB insert / update that uses an object to overwrite data
* use underscore _.pick() function

## Notes
Minos.Challenge.accept() >>> Meteor.call('challengeAccept', ....) >>> some server side function

**Comment by vrundbaken** [comment]
All fixed!
